# Generated by Django 3.1.7 on 2021-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
