# Generated by Django 3.1.7 on 2021-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_short_url_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
